# Generated by Django 5.2.6 on 2025-11-03 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('complaints', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.IntegerField()),
                ('message', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('owner_image', models.FileField(upload_to='')),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_phno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('owner_image', models.FileField(upload_to='')),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_phno', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('turf_type', models.CharField(max_length=50)),
                ('surface_type', models.CharField(max_length=50)),
                ('lighting', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.FileField(upload_to='')),
                ('license', models.FileField(upload_to='')),
                ('password', models.CharField(max_length=50)),
                ('phno', models.IntegerField()),
                ('pricing', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('no_of_slots', models.IntegerField()),
                ('s_time', models.IntegerField()),
                ('e_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phno', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
