# Generated by Django 5.2.6 on 2025-11-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.CharField(max_length=200),
        ),
    ]
