# Generated by Django 5.2.6 on 2025-11-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_complaint_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='status',
            new_name='action',
        ),
    ]
