# Generated by Django 5.2.6 on 2025-11-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_status_complaint_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='action',
            new_name='status',
        ),
    ]
