# Generated by Django 5.2.6 on 2025-11-05 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_action_complaint_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='cont',
        ),
        migrations.DeleteModel(
            name='complaint',
        ),
        migrations.DeleteModel(
            name='reply',
        ),
    ]
