# Generated by Django 5.2.6 on 2025-11-05 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_contact_cont_delete_complaint_delete_reply'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cont',
            new_name='contact_admin',
        ),
    ]
