# Generated by Django 5.2.6 on 2025-11-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_cont_contact_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_admin',
            name='status',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
