# Generated by Django 5.2.6 on 2025-11-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='pricing',
            field=models.IntegerField(),
        ),
    ]
